# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Addmemberdialoge.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QDialog {background-color: qlineargradient(spread:pad, x1:0.523045, y1:0, x2:0.522, y2:0.994318, stop:0 rgba(6, 136, 165, 255), stop:1 rgba(5, 100, 189, 155))}")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(21, 20, 170, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:22px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:20px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(307, 89, 30, 30))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Image/plus 1.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 150, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:20px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(307, 160, 30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Image/plus 1.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 223, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:20px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(307, 229, 30, 30))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Image/plus 1.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "Add a Member"))
        self.label_9.setText(_translate("Dialog", "Utkarsh Agrawal"))
        self.label_10.setText(_translate("Dialog", "Shanu Chourasiya"))
        self.label_11.setText(_translate("Dialog", "Vedant Khandelwal"))
import Resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
