# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogprojectcreate.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 250)
        Dialog.setStyleSheet("QDialog {background-color: qlineargradient(spread:pad, x1:0.523045, y1:0, x2:0.522, y2:0.994318, stop:0 rgba(6, 136, 165, 255), stop:1 rgba(5, 100, 189, 155))}")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(14, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:18px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:16px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 103, 181, 28))
        self.lineEdit_5.setStyleSheet("*{position: absolute;\n"
"width: 480.03px;\n"
"height: 61.14px;\n"
"left: 481.64px;\n"
"top: 398.27px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);}")
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(84, 178, 181, 28))
        self.pushButton.setStyleSheet("*{position: absolute;\n"
"width: 491.98px;\n"
"height: 57.64px;\n"
"left: 475.66px;\n"
"top: 657.15px;\n"
"\n"
"background: #13ADCF;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(144, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:16px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "Create a  Project"))
        self.label_9.setText(_translate("Dialog", "Project Name"))
        self.label_4.setText(_translate("Dialog", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
