# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insidecard1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(830, 620)
        Dialog.setStyleSheet("QDialog {background-color: qlineargradient(spread:pad, x1:0.523045, y1:0, x2:0.522, y2:0.994318, stop:0 rgba(6, 136, 165, 255), stop:1 rgba(5, 100, 189, 155))}")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(120, 445, 560, 120))
        self.plainTextEdit.setStyleSheet("position: absolute;\n"
"width: 903.46px;\n"
"height: 163.57px;\n"
"left: 218.27px;\n"
"top: 750.74px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"border-radius: 2px;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 418, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("*{\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(120, 120, 300, 90))
        self.plainTextEdit_2.setStyleSheet("position: absolute;\n"
"width: 397.59px;\n"
"height: 101.76px;\n"
"left: 218.27px;\n"
"top: 248.18px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"border-radius: 2px;\n"
"")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(580, 120, 150, 90))
        self.plainTextEdit_3.setStyleSheet("position: absolute;\n"
"width: 397.59px;\n"
"height: 101.76px;\n"
"left: 218.27px;\n"
"top: 248.18px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"border-radius: 2px;\n"
"")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(641, 135, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Image/plus 1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(617, 175, 91, 16))
        self.label_3.setStyleSheet("*{\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 12px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 280, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("*{\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(120, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("*{\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"}")
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(154, 310, 41, 41))
        self.plainTextEdit_4.setStyleSheet("position: absolute;\n"
"width: 397.59px;\n"
"height: 101.76px;\n"
"left: 218.27px;\n"
"top: 248.18px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"border-radius: 2px;\n"
"")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(158, 315, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Image/plus 1.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(620, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("*{\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(130, 450, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("*{\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 14px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(130, 126, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("*{\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 14px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"}")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add a Comment"))
        self.label_3.setText(_translate("Dialog", "Add Deadline"))
        self.label_4.setText(_translate("Dialog", "Add a Member"))
        self.label_5.setText(_translate("Dialog", "Add Description"))
        self.label_7.setText(_translate("Dialog", "Deadline"))
        self.label_8.setText(_translate("Dialog", "Write your comment here...."))
        self.label_9.setText(_translate("Dialog", "Add a description...."))
import Resource_rc
