# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(830, 620)
        Dialog.setStyleSheet("QDialog {background-color: qlineargradient(spread:pad, x1:0.523045, y1:0, x2:0.522, y2:0.994318, stop:0 rgba(6, 136, 165, 255), stop:1 rgba(5, 100, 189, 155))}")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(90, 90, 300, 350))
        self.listWidget.setStyleSheet("*{position: absolute;\n"
"width: 513.72px;\n"
"height: 529.59px;\n"
"left: 196.23px;\n"
"top: 200.18px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"box-shadow: 0px 4px 4px rgba(255, 255, 255, 0.3);\n"
"border-radius: 15px;}")
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 150, 301, 41))
        self.pushButton.setAcceptDrops(False)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("*{position: absolute;\n"
"width: 97.92px;\n"
"height: 43.39px;\n"
"left: 276.53px;\n"
"top: 278.95px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 14px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/utkar/Users/utkar/OneDrive/Desktop/Interactions/Mask Group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 204, 301, 41))
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("*{position: absolute;\n"
"width: 97.92px;\n"
"height: 43.39px;\n"
"left: 276.53px;\n"
"top: 278.95px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 14px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"}")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setAutoRepeat(True)
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 258, 301, 41))
        self.pushButton_3.setAcceptDrops(False)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("*{position: absolute;\n"
"width: 97.92px;\n"
"height: 43.39px;\n"
"left: 276.53px;\n"
"top: 278.95px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 14px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"}")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setAutoRepeat(True)
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 310, 301, 41))
        self.pushButton_4.setAcceptDrops(False)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("*{position: absolute;\n"
"width: 97.92px;\n"
"height: 43.39px;\n"
"left: 276.53px;\n"
"top: 278.95px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 14px;\n"
"line-height: 37px;\n"
"color: white;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"}")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setAutoRepeat(True)
        self.pushButton_4.setDefault(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(90, 130, 301, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 110, 47, 13))
        self.label.setStyleSheet("*{position: absolute;\n"
"width: 86.79px;\n"
"height: 43.39px;\n"
"left: 213.45px;\n"
"top: 214.88px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 37px;\n"
"\n"
"color: #FFFFFF;}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(516, 479, 131, 16))
        self.label_2.setStyleSheet("*{position: absolute;\n"
"width: 86.79px;\n"
"height: 43.39px;\n"
"left: 213.45px;\n"
"top: 214.88px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 37px;\n"
"\n"
"color: #FFFFFF;}")
        self.label_2.setObjectName("label_2")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(430, 439, 300, 131))
        self.listWidget_2.setStyleSheet("*{position: absolute;\n"
"width: 513.72px;\n"
"height: 529.59px;\n"
"left: 196.23px;\n"
"top: 200.18px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);\n"
"box-shadow: 0px 4px 4px rgba(255, 255, 255, 0.3);\n"
"border-radius: 15px;}")
        self.listWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(560, 509, 41, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Image/plus 1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(222, 397, 30, 30))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Image/plus 1.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(171, 368, 141, 16))
        self.label_5.setStyleSheet("*{position: absolute;\n"
"width: 86.79px;\n"
"height: 43.39px;\n"
"left: 213.45px;\n"
"top: 214.88px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 16px;\n"
"line-height: 37px;\n"
"\n"
"color: #FFFFFF;}")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        self.listWidget.setCurrentRow(-1)
        self.listWidget_2.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.listWidget.setSortingEnabled(True)
        self.pushButton.setText(_translate("Dialog", "Card 1"))
        self.pushButton_2.setText(_translate("Dialog", "Card 2"))
        self.pushButton_3.setText(_translate("Dialog", "Card 3"))
        self.pushButton_4.setText(_translate("Dialog", "Card 4"))
        self.label.setText(_translate("Dialog", "List 1"))
        self.label_2.setText(_translate("Dialog", "Add a New List"))
        self.listWidget_2.setSortingEnabled(True)
        self.label_5.setText(_translate("Dialog", "Add a New Card"))
import Resource_rc
