# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(830, 620)
        Dialog.setStyleSheet("QDialog {background-color: qlineargradient(spread:pad, x1:0.523045, y1:0, x2:0.522, y2:0.994318, stop:0 rgba(6, 136, 165, 255), stop:1 rgba(5, 100, 189, 155))}")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(309, 135, 300, 28))
        self.lineEdit.setStyleSheet("*{position: absolute;\n"
"width: 480.03px;\n"
"height: 61.14px;\n"
"left: 481.64px;\n"
"top: 398.27px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);}")
        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 507, 300, 28))
        self.pushButton.setStyleSheet("*{position: absolute;\n"
"width: 491.98px;\n"
"height: 57.64px;\n"
"left: 475.66px;\n"
"top: 657.15px;\n"
"\n"
"background: #13ADCF;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(425, 503, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:64 px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(308, 199, 300, 28))
        self.lineEdit_2.setStyleSheet("*{position: absolute;\n"
"width: 480.03px;\n"
"height: 61.14px;\n"
"left: 481.64px;\n"
"top: 398.27px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);}")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(311, 138, 20, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Image/person.svg"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(370, 50, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:64 px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(309, 201, 21, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Image/lock.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(307, 271, 300, 28))
        self.lineEdit_3.setStyleSheet("*{position: absolute;\n"
"width: 480.03px;\n"
"height: 61.14px;\n"
"left: 481.64px;\n"
"top: 398.27px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);}")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(307, 341, 300, 28))
        self.lineEdit_4.setStyleSheet("*{position: absolute;\n"
"width: 480.03px;\n"
"height: 61.14px;\n"
"left: 481.64px;\n"
"top: 398.27px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);}")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(307, 411, 300, 28))
        self.lineEdit_5.setStyleSheet("*{position: absolute;\n"
"width: 480.03px;\n"
"height: 61.14px;\n"
"left: 481.64px;\n"
"top: 398.27px;\n"
"\n"
"background: rgba(255, 255, 255, 0.3);}")
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(307, 273, 21, 21))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Image/lock.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(309, 344, 21, 21))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Image/email.svg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(200, 123, 100, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:64 px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(203, 187, 100, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:64 px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(132, 260, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:64 px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(163, 327, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:64 px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(159, 400, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("*{position: absolute;\n"
"width: 217.37px;\n"
"height: 88.31px;\n"
"left: 606.99px;\n"
"top: 269.2px;\n"
"\n"
"font-family: Montserrat;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size:64 px;\n"
"line-height: 78px;\n"
"\n"
"color: #FFFFFF;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(310, 414, 21, 21))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Image/phone 1.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Register"))
        self.label_3.setText(_translate("Dialog", "Register"))
        self.label_8.setText(_translate("Dialog", "Username"))
        self.label_9.setText(_translate("Dialog", "Password"))
        self.label_10.setText(_translate("Dialog", "Re-type Password"))
        self.label_11.setText(_translate("Dialog", "Email Address"))
        self.label_12.setText(_translate("Dialog", "Phone Number"))
import Resource_rc
